#!/usr/bin/env bash
# Generate lexical structure maps for load-bearing scripts.
# Maps are structure only; they do NOT prove runtime reachability, safety, or auth.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
MAPDIR="$ROOT/analysis/maps"
mkdir -p "$MAPDIR"

list_file="$MAPDIR/scripts.cscope.files"
: > "$list_file"

shopt -s nullglob
scripts=("$ROOT"/scripts/*.sh)
if [[ ${#scripts[@]} -eq 0 ]]; then
  echo "no scripts to map" >&2
  exit 1
fi

# Stable sort for reproducible maps
mapfile -t scripts < <(printf '%s\n' "${scripts[@]}" | sort)

for s in "${scripts[@]}"; do
  # cscope wants relative or absolute paths; store repo-relative for portability
  echo "${s#$ROOT/}" >> "$list_file"
done

{
  echo "# Lexical map of scripts (shell). Generated by gen-maps.sh"
  echo "# NONCLAIM: not a C call graph; not runtime reachability or security proof."
  echo "# generated_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# script_count=${#scripts[@]}"
  for s in "${scripts[@]}"; do
    rel=${s#$ROOT/}
    echo
    echo "## FILE $rel"
    echo "# sha256 $(sha256sum "$s" | awk '{print $1}')"
    # shell function names
    rg -n '^[a-zA-Z_][a-zA-Z0-9_]*\s*\(\)\s*\{' "$s" || true
    rg -n '^\s*(source|\.)\s+' "$s" || true
    # external command invocations that matter for bootstrap
    rg -n '\b(qemu-system-x86_64|pacman|makepkg|settrans|mkfs|mount|git|curl|configure|make)\b' "$s" || true
  done
} > "$MAPDIR/scripts.cflow.txt"

# Per-script inventory TSV (path, functions, bytes, sha256)
inv="$MAPDIR/scripts.inventory.tsv"
echo -e "path\tfunctions\tbytes\tsha256" > "$inv"
for s in "${scripts[@]}"; do
  rel=${s#$ROOT/}
  nfunc=$(rg -c '^[a-zA-Z_][a-zA-Z0-9_]*\s*\(\)\s*\{' "$s" 2>/dev/null || echo 0)
  # rg -c prints nothing if zero matches sometimes; normalize
  [[ -z "$nfunc" || "$nfunc" == "0" ]] && nfunc=$(rg -c '^[a-zA-Z_][a-zA-Z0-9_]*\s*\(\)\s*\{' "$s" || true)
  nfunc=${nfunc:-0}
  bytes=$(wc -c < "$s" | tr -d ' ')
  sum=$(sha256sum "$s" | awk '{print $1}')
  echo -e "${rel}\t${nfunc}\t${bytes}\t${sum}" >> "$inv"
done

# Real cflow if any C sources appear
c_list=()
while IFS= read -r -d '' f; do
  c_list+=("$f")
done < <(find "$ROOT/tools" "$ROOT/packages" -name '*.c' -print0 2>/dev/null || true)

if [[ ${#c_list[@]} -gt 0 ]] && command -v cflow >/dev/null 2>&1; then
  (cd "$ROOT" && cflow "${c_list[@]}" > "$MAPDIR/c-sources.cflow.txt") || \
    echo "# cflow failed (non-fatal)" > "$MAPDIR/c-sources.cflow.txt"
else
  echo "# no C sources yet (or cflow missing)" > "$MAPDIR/c-sources.cflow.txt"
fi

# cscope index from file list (paths relative to MAPDIR fail; use absolute for build)
cscope_list="$MAPDIR/scripts.cscope.files.abs"
: > "$cscope_list"
for s in "${scripts[@]}"; do
  echo "$s" >> "$cscope_list"
done
if command -v cscope >/dev/null 2>&1; then
  (cd "$MAPDIR" && cscope -b -i scripts.cscope.files.abs -f scripts.cscope.out) || true
fi

# optional ctags on scripts for symbol sketch
if command -v ctags >/dev/null 2>&1; then
  ctags -f "$MAPDIR/scripts.tags" --languages=Sh "${scripts[@]}" 2>/dev/null || true
fi

cat > "$MAPDIR/NONCLAIM.txt" <<'EOF'
These maps are lexical structure only.
They do not prove runtime reachability, authorization, safety, or hardware behavior.
Regenerate with: make maps
EOF

manifest="$MAPDIR/MAP_MANIFEST.tsv"
echo -e "path\ttool\tsha256\tbytes" > "$manifest"
for f in \
  "$MAPDIR/scripts.cflow.txt" \
  "$MAPDIR/scripts.cscope.files" \
  "$MAPDIR/scripts.inventory.tsv" \
  "$MAPDIR/c-sources.cflow.txt" \
  "$MAPDIR/NONCLAIM.txt"
 do
  [[ -f "$f" ]] || continue
  sum=$(sha256sum "$f" | awk '{print $1}')
  bytes=$(wc -c < "$f" | tr -d ' ')
  echo -e "${f#$ROOT/}\tgen-maps.sh\t${sum}\t${bytes}" >> "$manifest"
done

# Verify every scripts/*.sh is listed in inventory
missing=0
for s in "${scripts[@]}"; do
  rel=${s#$ROOT/}
  if ! awk -F'\t' -v p="$rel" 'NR>1 && $1==p {found=1} END{exit !found}' "$inv"; then
    echo "map inventory missing $rel" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  exit 2
fi

echo "maps written under $MAPDIR (scripts=${#scripts[@]})"
